### ISSUE TITLE
Add Shelf.nu (Asset / Equipment Management and Location Tracking Software)

### ISSUE THREAD

**Issue by carlosvirreira** [awesome-selfhosted/awesome-selfhosted-data#241]
Thanks for taking the time to suggest an addition to awesome-selfhosted! 

Please fill out information below (all fields are mandatory unless noted otherwise):

```yaml
# Shelf.nu
name: "Shelf - Asset Management Infrastructure for Everyone"
# URL of the software project's homepage
website_url: "https://www.shelf.nu"
# URL where the full source code of the program can be downloaded
source_code_url: "https://github.com/Shelf-nu/shelf.nu"
# description of what the software does, shorter than 250 characters, sentence case
description: "Asset and Equipment tracking software used by teams who value clarity. Shelf is an asset database and QR asset label generator that lets you create, manage and overview your assets across locations. Unlimited assets, free forever."
# list of license identifiers, see https://github.com/awesome-selfhosted/awesome-selfhosted-data/blob/master/licenses.yml for the full list of licenses
licenses:
  - AGPL-3.0
# list of languages/platforms, see https://github.com/awesome-selfhosted/awesome-selfhosted-data/tree/master/platforms for the full list of platforms
platforms:
- Javascript
# list of tags (categories), see https://github.com/awesome-selfhosted/awesome-selfhosted-data/tree/master/tags for the full list of tags
tags:
  - Automation
  - Inventory-management

# (optional, yes/no, default no) whether the software depends on a third-party service outside the user's control
depends_3rdparty: yes
# (optional) link to an interactive demo of the software
demo_url: "-"
# (optional) link to a list of clients/addons/plugins/apps/bots... for the software
related_software_url: "-"
```

To ensure your issue is dealt with swiftly, please check the following (check the boxes `[x]`):
- [x] Submit one item per pull issue. This eases reviewing and speeds up inclusion.
- [x] You have searched the repository for any relevant [issues](https://github.com/awesome-selfhosted/awesome-selfhosted-data/issues) or [PRs](https://github.com/awesome-selfhosted/awesome-selfhosted-data/pulls), including closed ones.
- [x] Any software you are adding is not already listed at any of [awesome-sysadmin](https://github.com/n1trux/awesome-sysadmin), [staticgen.com](https://www.staticgen.com/), [staticsitegenerators.net](https://staticsitegenerators.net/), [dbdb.io](https://dbdb.io/browse).
- [x] Any software project you are adding to the list is actively maintained.
- [ ] Any software project you are adding was first released more than 4 months ago.
- [x] Any software project you are adding has working installation instructions.
- [x] If you are adding software forked from another active project, please provide/link to a clear list of differences between both.

**Comment by nodiscc** [comment]
Initial release on July 24, 2023 (https://github.com/Shelf-nu/shelf.nu/releases?page=2) - must reach the 4 months threshold before this can be checked again

**Comment by vela81** [comment]
[iii]()

**Comment by KieranRobson** [comment]
To be revisited: `24 November 2023`

**Comment by Ki-er** [comment]
This is now mature enough.

**Comment by carlosvirreira** [comment]
Nice, would be cool to enter the list!
